name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o title_creator-linux

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o title_creator

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o title_creator.exe

      - name: Archive Builds
        run: |
          mkdir builds
          mv title_creator-linux builds/
          mv title_creator builds/
          mv title_creator.exe builds/
        working-directory: ${{ github.workspace }}

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: builds

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          generate_release_notes:  true
          files: builds/*
          prerelease: false
          token: ${{ secrets.GO_TITLES_BUILD }}

