name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Create Archive Dir
        run: |
          mkdir archives

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o title_creator

      - name: Create Linux Archives
        run: |
          mkdir archives
          tar -czvf archives/title_creator-linux.tar.gz title_creator
        working-directory: ${{ github.workspace }}

      - name: Build for macOS x86
        run: GOOS=darwin GOARCH=amd64 go build -o title_creator

      - name: Create macos Archives x86
        run: |
          mkdir archives
          tar -czvf archives/title_creator-macos-intel.tar.gz title_creator
        working-directory: ${{ github.workspace }}

      - name: Build for macOS Arm
        run: GOOS=darwin GOARCH=arm64 go build -o title_creator

      - name: Create macos Archives Arm
        run: |
          mkdir archives
          tar -czvf archives/title_creator-macos-arm.tar.gz title_creator
        working-directory: ${{ github.workspace }}

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o title_creator.exe

      - name: Create Windows Archives
        run: |
          mkdir archives
          zip -r archives/title_creator-windows.zip title_creator.exe
        working-directory: ${{ github.workspace }}

      - name: Move Archives to Builds
        run: mv archives/* builds/
        working-directory: ${{ github.workspace }}

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: builds

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          generate_release_notes:  true
          files: archives/*
          prerelease: false
          token: ${{ secrets.GO_TITLES_BUILD }}

