name: Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release"
        required: true
        default: "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Create Archive and Builds Dir
        run: |
          mkdir archives
          mkdir builds

      - name: Copy readme
        run: |
          cp README.md builds/

      - name: Build for Linux x86
        run: GOOS=linux GOARCH=amd64 go build -o title_creator title_creator.go winsize_nix.go

      - name: Create Linux Archives x86
        run: |
          tar -czvf archives/title_creator-linux_x86_64.tar.gz title_creator README.md *.json *.map
        working-directory: ${{ github.workspace }}

      - name: Build for Linux arm64
        run: GOOS=linux GOARCH=arm64 go build -o title_creator title_creator.go winsize_nix.go

      - name: Create Linux Archives arm64
        run: |
          tar -czvf archives/title_creator-linux_arm64.tar.gz title_creator README.md *.json *.map
        working-directory: ${{ github.workspace }}

      - name: Build for macOS x86
        run: GOOS=darwin GOARCH=amd64 go build -o title_creator title_creator.go winsize_nix.go

      - name: Create macos Archives x86
        run: |
          tar -czvf archives/title_creator-macos-intel.tar.gz title_creator README.md *.json *.map
        working-directory: ${{ github.workspace }}

      - name: Build for macOS Arm
        run: GOOS=darwin GOARCH=arm64 go build -o title_creator title_creator.go winsize_nix.go

      - name: Create macos Archives Arm
        run: |
          tar -czvf archives/title_creator-macos-arm.tar.gz title_creator README.md *.json *.map
        working-directory: ${{ github.workspace }}

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o title_creator.exe title_creator.go winsize_win.go

      - name: Create Windows Archives
        run: |
          zip -r archives/title_creator-windows.zip title_creator.exe README.md *.json *.map
        working-directory: ${{ github.workspace }}

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: archives
          path: archives

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes:  true
          files: archives/*
          prerelease: false
          token: ${{ secrets.GO_TITLES_BUILD }}

